class_name CardEnums
extends RefCounted

enum CardColor { RED, GREEN, PURPLE }

enum ConditionType {
	NONE,
	NEXT_IS_COLOR,
	ADJACENT_COUNT_COLOR,
	COLOR_AFTER_COUNT,
	CASSETTES_BEFORE_COUNT,
	HAS_ADJACENT_COLOR,
	NO_ADJACENT_COLOR,
	NOT_LAST_IN_CHAIN,
	ENEMY_INTENTS_DAMAGE,
	ENEMY_INTENTS_BLOCK,
}

enum StatusType { NONE, VULNERABLE, WEAKNESS, PROTECTION, STRENGTH, BLOCK }
